/**
 * Single source of truth for the Respira MCP tool count surfaced in the CLI.
 *
 * Centralized so the welcome screen, error messages, and any future surface
 * can read the same value. Update with each release that adds tools. The
 * authoritative catalog lives at product-website/src/data/tools-catalog.ts
 * and is regenerated by scripts/tools-catalog/02-generate.mjs.
 *
 * @since 0.1.4
 */
export const TOTAL_TOOLS = 234;
